### ISSUE TITLE
Error: All values in `table` must be nonnegative.

### ISSUE THREAD

**Issue by sjroth** [tanghaibao/goatools#115]
Not sure why this error is occurring as I've used the following code in multiple contexts... Please advise:
obo_fname = download_go_basic_obo()
gene2go = download_ncbi_associations()
obodag = GODag("go-basic.obo")
geneid2gos = read_ncbi_gene2go("gene2go",taxids=[9606])
goeaobj = GOEnrichmentStudy(GeneID2nt.keys(),geneid2gos,obodag,propagate_counts=False,alpha=0.05,methods=['fdr_bh'])

goea_results = goeaobj.run_study(geneids)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-62d832a06362> in <module>
----> 1 goea_results = goeaobj.run_study(geneids)

/gpfs/data01/bennerlab/home/sjroth/software/miniconda3/lib/python3.6/site-packages/goatools/go_enrichment.py in run_study(self, study, **kws)
    273         log = kws['log'] if 'log' in kws else self.log
    274         # Calculate uncorrected pvalues
--> 275         results = self.get_pval_uncorr(study, log)
    276         if not results:
    277             return []

/gpfs/data01/bennerlab/home/sjroth/software/miniconda3/lib/python3.6/site-packages/goatools/go_enrichment.py in get_pval_uncorr(self, study, log)
    336             one_record = GOEnrichmentRecord(
    337                 GO=term,
--> 338                 p_uncorrected=calc_pvalue(study_count, study_n, pop_count, pop_n),
    339                 study_items=study_items,
    340                 pop_items=pop_items,

/gpfs/data01/bennerlab/home/sjroth/software/miniconda3/lib/python3.6/site-packages/goatools/pvalcalc.py in calc_pvalue(self, study_count, study_n, pop_count, pop_n)
     65         d = pop_n - pop_count - b
     66         # stats.fisher_exact returns oddsratio, pval_uncorrected
---> 67         _, p_uncorrected = self.pval_fnc( [[a, b], [c, d]])
     68         return p_uncorrected
     69 

/gpfs/data01/bennerlab/home/sjroth/software/miniconda3/lib/python3.6/site-packages/scipy/stats/stats.py in fisher_exact(table, alternative)
   3088 
   3089     if np.any(c < 0):
-> 3090         raise ValueError("All values in `table` must be nonnegative.")
   3091 
   3092     if 0 in c.sum(axis=0) or 0 in c.sum(axis=1):

ValueError: All values in `table` must be nonnegative.

The geneids are the following: 
[6405, 56603, 23098, 114881, 3475, 115098, 57585, 29116, 9918, 11188, 51099, 54831, 6558, 2261, 5837, 10420, 4034, 4850, 5663, 55054, 56605, 4849, 2521, 6548, 55632, 255057, 2872, 8940, 55671, 5360, 5973, 11040, 8874, 26512, 83716, 4741, 26093, 29997, 7087, 51678, 3955, 8887, 4885, 27338, 9400, 51655, 8050, 6404, 51561, 6539, 63914, 10087, 80321, 10057, 1181, 84812, 2043, 54856, 2309, 5228, 80209, 80298, 50836, 50839, 50835, 7750, 3181, 11059, 6615, 26212, 3659, 8744, 2354, 54429, 7538, 4289, 9667, 57688, 85441, 84660, 6535, 55037, 3679, 9958, 5077, 55627, 9394, 8027, 84904, 2959, 1134, 10152, 23162, 6843, 84915, 22893, 84166, 2774, 22994, 3339, 51454, 114790, 185, 9353, 54540, 168374, 93953, 92129, 54805, 775, 10570, 284306, 79819, 10018, 1070, 285172, 130540, 64319, 2585, 1974, 6497, 56946, 149483, 353355, 83858, 2232, 113251, 4041, 467, 55249, 57018, 4241, 27236, 2898, 203522, 8559, 6621, 717, 6236, 64772, 3906, 8085, 154, 2194, 3684, 83756, 2353, 153572, 8493, 4884, 3400, 80765, 387357, 8793, 80311, 169166, 400986, 388730, 55279, 146177, 22877, 10458, 163259, 1479, 29882, 8851, 389289, 9772, 1104, 23060, 284083, 9370, 7262, 389692, 54880, 57634, 728411, 84851, 339416, 130502, 26039, 116447, 752, 8651, 255812, 26013, 730094, 23396, 55693, 10614, 3010, 2175, 23036, 391104, 196528, 644943, 9687, 6261, 8295, 7678, 4122, 147686, 85301, 29950, 107983990, 83875, 147741, 54870, 192134, 23237, 767577, 677840, 767568, 677846, 26835, 767578, 26821, 6084, 767585, 109616970, 677839, 677801, 767563, 767569, 125050, 101954278, 6085, 56662, 2550, 790955, 554251, 440944, 26864, 26827, 100033430, 677797, 100033425, 103625684, 101954271, 407000, 619555, 574038, 677841, 677800, 9534, 151295, 55384, 751071, 283551, 100130742, 109617000, 101929145, 283416, 109616976, 105374219, 284391, 80772, 26777, 651302, 400619, 102724919, 643749, 101928820, 54147, 643180, 618, 101927055, 692223, 677767, 677777, 652966, 677828, 692084, 100124534, 283507, 5297, 727956, 391123, 339894, 106479524, 101928445, 283131, 1050, 286059, 503569, 102723562, 102577426, 100507291, 378938, 677772, 677768, 677681, 677679, 347051, 619383, 735301, 102724064, 401258, 100463488, 105375015, 7556, 100506606, 102723619, 100506071, 4360, 105371184, 642658, 283932, 100422899, 26851, 100847004, 100847003, 83593, 105376843, 103091864, 8517, 10984, 100463482, 378706, 692215, 100033820, 677766, 378707, 100126299, 145624, 100861563, 126661, 780854, 101241892, 100302221, 100616406, 693197, 102466854]

**Comment by dvklopfenstein** [comment]
Thank your interest in GOATOOLS and for taking the time to write us.

This was an issue as reported in #96 , and we beleive have been fixed. What version of goatools do you have?

```
>>> import goatools
>>> print(goatools.__version__)
0.8.9
```

If your goatools version is less tha 0.8.9, please try updating and let us know what you see.

Thank you for reporting this. We look forward to hearing more.

**Comment by sjroth** [comment]
Sorry for the late response. I updated to that version and I am still getting the same error.

**Comment by sjroth** [comment]
Never mind. It was resolved. Thanks!

**Comment by dvklopfenstein** [comment]
That is good news that the issue was resolved. Please feel free to open a new issue if you see it in the future.

Thank you for your interest in GOATOOLS and for taking the time to write us.
